// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwAbRC-PIVUCUjWlMxX-d1wbfOyVxYAY',
    appId: '1:46358823994:web:de72f3c84e7f27b62c2103',
    messagingSenderId: '46358823994',
    projectId: 'pet-clinic-appointment-4652c',
    authDomain: 'pet-clinic-appointment-4652c.firebaseapp.com',
    storageBucket: 'pet-clinic-appointment-4652c.firebasestorage.app',
    measurementId: 'G-F0FJLX4ZL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQRUhLWIyG62QRJkDbftcjuSxsrFMRNV0',
    appId: '1:46358823994:android:0dcfdb3cb069905f2c2103',
    messagingSenderId: '46358823994',
    projectId: 'pet-clinic-appointment-4652c',
    storageBucket: 'pet-clinic-appointment-4652c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmQ8AlFzCn_XkYjeT37ZefUx3uMP34nhM',
    appId: '1:46358823994:ios:2022f27b6e2a775e2c2103',
    messagingSenderId: '46358823994',
    projectId: 'pet-clinic-appointment-4652c',
    storageBucket: 'pet-clinic-appointment-4652c.firebasestorage.app',
    iosBundleId: 'com.example.userLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmQ8AlFzCn_XkYjeT37ZefUx3uMP34nhM',
    appId: '1:46358823994:ios:2022f27b6e2a775e2c2103',
    messagingSenderId: '46358823994',
    projectId: 'pet-clinic-appointment-4652c',
    storageBucket: 'pet-clinic-appointment-4652c.firebasestorage.app',
    iosBundleId: 'com.example.userLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgwAbRC-PIVUCUjWlMxX-d1wbfOyVxYAY',
    appId: '1:46358823994:web:c59a812bab56e9592c2103',
    messagingSenderId: '46358823994',
    projectId: 'pet-clinic-appointment-4652c',
    authDomain: 'pet-clinic-appointment-4652c.firebaseapp.com',
    storageBucket: 'pet-clinic-appointment-4652c.firebasestorage.app',
    measurementId: 'G-ZBG7TR2Z7Q',
  );
}
